schema_version = "1.0.0"

id = "gitmass_tree"
version = "1.0.0"
name = "Gitmass Tree"
tagline = "Git履歴からクリスマスツリーを生成します"
maintainer = "Hiroshi Minakata"
type = "add-on"
tags = ["Object"]

blender_version_min = "4.2.0"
blender_version_max = "6.0.0"

license = ["SPDX:GPL-3.0-or-later"]